#pragma config(Sensor, dgtl1,  bumper,         sensorTouch)
#pragma config(Motor,  port1,           a,             tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           motor1,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           motor2,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           d,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           e,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           f,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           g,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           h,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           i,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          j,             tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
	// Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
	// .....................................................................................
	// Insert user code here.
	// .....................................................................................

	AutonomousCodePlaceholderForTesting();  // Remove this function call once you have "real" code.
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	// User control code here, inside the loop

	while (true)
	{
		// Pull back kicker until it bumps bumper, then hold it there
		// Continue pulling when button pressed (reaches end of teeth on gear and fires)
		if(!SensorValue[bumper])
		{
			// Pull back
			motor[motor1] = motor[motor2] = 127;
		}
		else if(!vexRT[Btn8D])
		{
			// Hold in place
			motor[motor1] = motor[motor2] = 10;
		}
		else
		{
			// Fire!
			motor[motor1] = motor[motor2] = 127;
		}
	}
}
