#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    armPoten,       sensorPotentiometer)
#pragma config(Sensor, in2,    RarmPoten,      sensorPotentiometer)
#pragma config(Sensor, dgtl1,  liftPoten,      sensorNone)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port2,           FLWheel,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           RArm,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           BLWheel,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           LBLift,        tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_2)
#pragma config(Motor,  port6,           RBLift,        tmotorVex393_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port7,           BRWheel,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           LArm,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           FRWheel,       tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

//User Created Tasks
//task gripControl();
int liftPotenVal = 0;
int armPotenVal = 0;
int RarmPotenVal = 0;

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;
  slaveMotor ( LBLift, RBLift );

}

task autonomous()
{

}

task usercontrol()
{
	int creep = 25;
	while (true)
	{
		motor[RArm] = ( vexRT[Btn5U] - vexRT[Btn5D] ) * 40;
		motor[LArm] = ( vexRT[Btn5U] - vexRT[Btn5D] ) * 40;
		motor[RBLift] = ( vexRT[Btn6U] - vexRT[Btn6D] ) * 127;
		liftPotenVal = nMotorEncoder[RBLift];
		armPotenVal = SensorValue(armPoten);
		RarmPotenVal = SensorValue(RarmPoten);
		//Reset Lift Encoder
		if (vexRT[Btn8U]) { SensorValue(liftPoten) = 0; }

		//Drive Wheels
		if ((vexRT[Ch3] < creep) && (vexRT[Ch3] >-creep) && (vexRT[Ch4] < creep) && (vexRT[Ch4] >-creep)){motor[FLWheel] = 0;} else {motor[FLWheel] = vexRT[Ch3] + vexRT[Ch4]; }
		if ((vexRT[Ch3] < creep) && (vexRT[Ch3] >-creep) && (vexRT[Ch1] < creep) && (vexRT[Ch1] >-creep)){motor[BLWheel] = 0;} else {motor[BLWheel] = vexRT[Ch3] - vexRT[Ch1]; }
		if ((vexRT[Ch2] < creep) && (vexRT[Ch2] >-creep) && (vexRT[Ch4] < creep) && (vexRT[Ch4] >-creep)){motor[FRWheel] = 0;} else {motor[FRWheel] = vexRT[Ch2] - vexRT[Ch4]; }
		if ((vexRT[Ch2] < creep) && (vexRT[Ch2] >-creep) && (vexRT[Ch1] < creep) && (vexRT[Ch1] >-creep)){motor[BRWheel] = 0;} else {motor[BRWheel] = vexRT[Ch2] + vexRT[Ch1]; }

	}
}
