#pragma config(Sensor, in1,    armPoten,       sensorPotentiometer)
#pragma config(Sensor, in2,    RarmPoten,      sensorPotentiometer)
#pragma config(Sensor, dgtl1,  liftPoten,      sensorQuadEncoder)
#pragma config(Motor,  port1,           BLWheel,       tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           FLWheel,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           LArm,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           LFLift,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           LBLift,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           RBLift,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           RFLift,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           RArm,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           FRWheel,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          FLWheel,       tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

//User Created Tasks
//task gripControl();
int liftPotenVal = 0;
int armPotenVal = 0;
int RarmPotenVal = 0;

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;
  slaveMotor ( RBLift, RFLift );
  slaveMotor ( LFLift, RFLift );
  slaveMotor ( LBLift, RFLift );
}

task autonomous()
{

}

task usercontrol()
{
	while (true)
	{
		motor[RArm] = ( vexRT[Btn5U] - vexRT[Btn5D] ) * 40;
		motor[LArm] = ( vexRT[Btn5U] - vexRT[Btn5D] ) * 40;
		motor[RFLift] = ( vexRT[Btn6U] * 40 - vexRT[Btn6D] * -20);
		liftPotenVal = SensorValue(liftPoten);
		armPotenVal = SensorValue(armPoten);
		RarmPotenVal = SensorValue(RarmPoten);
		//Reset Lift Encoder
		if (vexRT[Btn8U]) { SensorValue(liftPoten) = 0; }

	}
}
