#pragma config(Sensor, in1,    armPoten,       sensorPotentiometer)
#pragma config(Sensor, dgtl1,  liftPoten,      sensorQuadEncoder)
#pragma config(Motor,  port2,           LUArm,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           LBLift,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           LFLift,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           LDArm,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           RBLift,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           RFLift,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           RDArm,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           RUArm,         tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

//User Created Tasks
//task gripControl();

//Global Variables
int armPotenVal = 2205;
int armPotenTarget = 2205;

int liftPotenVal = 0;
int liftPotenTarget = 0;

float KpArm = 0.000002;
float KiArm = 0;
float KdArm = 0.2;

float KpLift = 0.000000000002;
float KiLift = 0;
float KdLift = 2;

int mtrpowerArm = 0;
int mtrpowerLift = 0;

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;
  slaveMotor ( LDArm, RUArm );
  slaveMotor ( LUArm, RUArm );
  slaveMotor ( RDArm, RUArm );
  slaveMotor ( RBLift, RFLift );
  slaveMotor ( LFLift, RFLift );
  slaveMotor ( LBLift, RFLift );
}

task autonomous()
{

}

task usercontrol()
{
	//startTask(gripControl);
	//int rev = 127;

	//*********************************************************************************************************

	//Arm PID Variables
	int waitTime = 1;

	float TpArm = 0; //TUNABLE: [Starting] Power of right launcher
	float errorArm = 0; //Error of right launcher

	float iArm = 0; //Integral of right launcher

	float dArm = 0; //Derivative of right launcher
	float errorArmPrevious = 0;

	float editArm = 0; //Edit: How much to change right launch speed

	//Lift PID Variables
	float TpLift = 0; //TUNABLE: [Starting] Power of right launcher
	float errorLift = 0; //Error of right launcher

	float iLift = 0; //Integral of right launcher

	float dLift = 0; //Derivative of right launcher
	float errorLiftPrevious = 0;

	float editLift = 0; //Edit: How much to change right launch speed

	SensorValue(liftPoten) = 0;

	while (true)
	{
		wait1Msec(waitTime);

		//Arm PID ****************************************************************************************************

		errorArm = ( armPotenTarget - SensorValue(armPoten) ); // Error = Target - Observed

		if ((errorArm > 0 && errorArmPrevious < 0) || (errorArm < 0 && errorArmPrevious > 0) || (errorArm == 0))
		{
			iArm = 0;
		}

		if (abs(errorArm)>5)
		{
			playImmediateTone(600,5);
		}
		iArm = iArm + errorArm; // Integral = Integral + Error

		dArm = errorArm - errorArmPrevious; // Derivative = Error - PreviousError

		errorArmPrevious = errorArm;

		editArm = KpArm * errorArm + KiArm * iArm + KdArm * dArm; // Edit = Kp * Error + Ki * Integral + Kd * Derivative
		//if  ((TpRLaunch + editRightLaunch) > 0)
		//{
			motor[RUArm] = TpArm + editArm; // MotorPower = PreviousMotorPower + Edit
			TpArm += editArm; // MotorPower = PreviousMotorPower + Edit
		//}

		//get poten val!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
		armPotenVal = SensorValue(armPoten);
		mtrpowerArm = motor[RUArm];

		//Lift PID ***************************************************************************************************

		errorLift = ( liftPotenTarget - SensorValue(liftPoten) ); // Error = Target - Observed

		if ((errorLift > 0 && errorLiftPrevious < 0) || (errorLift < 0 && errorLiftPrevious > 0) || (errorLift == 0))
		{
			iLift = 0;
		}

		if (abs(errorLift)>5)
		{
			playImmediateTone(800,5);
		}
		iLift = iLift + errorLift; // Integral = Integral + Error

		dLift = errorLift - errorLiftPrevious; // Derivative = Error - PreviousError

		errorLiftPrevious = errorLift;

		editLift = KpLift * errorLift + KiLift * iLift + KdLift * dLift; // Edit = Kp * Error + Ki * Integral + Kd * Derivative
		if  ((TpLift + editLift) <= -20)
		{
			motor[RFLift] = -20;
			TpLift = TpLift + editLift;
		}
		else
		{
			motor[RFLift] = TpLift + editLift; // MotorPower = PreviousMotorPower + Edit
			TpLift = TpLift + editLift; // MotorPower = PreviousMotorPower + Edit
		}

		//get poten val!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
		liftPotenVal = SensorValue(liftPoten);
		mtrpowerLift = motor[RFLift];

		//*Driver Controls ************************************************************************************************

		//Set Target Arm Position
		if (vexRT[Btn7L]) { armPotenTarget = 550; } //closed
		else if (vexRT[Btn7U]) { armPotenTarget = 2205; } //middle
		else if (vexRT[Btn7R]) { armPotenTarget = 3453; } //start


		//Set Target Lift Position
		if (vexRT[Btn8L]) { liftPotenTarget = 0; } //full down 	poten4095
		else if (vexRT[Btn8U]) { liftPotenTarget = 20; } //down 	poten2978
		else if (vexRT[Btn8R]) { liftPotenTarget = 95; } //up   	poten1528

		//Reset Lift Encoder
		if (vexRT[Btn6U]) { SensorValue(liftPoten) = 0; liftPotenTarget = 0;}
	}
}
