#pragma config(Sensor, in1,    armPoten,       sensorPotentiometer)
#pragma config(Motor,  port1,           DL,            tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           UL,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           DR,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           UR,            tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

//Global Variables
int armPotenVal = 0;
int armPotenTarget = 0;

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;
}

task autonomous()
{

}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	int rev = 127;
	while (true)
	{
		//get poten val!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
		armPotenVal = SensorValue(armPoten);

		//Set Target Arm Position
		if (vexRT[Btn7L]) { armPotenTarget = 421; }
		else if (vexRT[Btn7U]) { armPotenTarget = 1877; }
		else if (vexRT[Btn7R]) { armPotenTarget = 3465; }

		//Independent Arm Motor Control
	  motor[UR] = vexRT[Btn6U] * rev + vexRT[Btn6D] * -rev;
	  motor[DR] = vexRT[Btn6U] * rev + vexRT[Btn6D] * -rev;
	  motor[UL] = vexRT[Btn6U] * rev + vexRT[Btn6D] * -rev;
	  motor[DL] = vexRT[Btn6U] * rev + vexRT[Btn6D] * -rev;
	}
}
