#pragma config(Sensor, in1,    armPoten,       sensorPotentiometer)
#pragma config(Motor,  port1,           DL,            tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           UL,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           DR,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           UR,            tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

//Global Variables
int armPotenVal = 0;
int armPotenTarget = 0;

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;
}

task autonomous()
{

}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	int rev = 1;
	while (true)
	{
		//get poten val!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
		armPotenVal = SensorValue(armPoten);

		//Set Target Arm Position
		if (vexRT[Btn7L]) { armPotenTarget = 574; }
		else if (vexRT[Btn7U]) { armPotenTarget = 2048; }
		else if (vexRT[Btn7R]) { armPotenTarget = 3522; }

		//Correct Arm

		//Independent Arm Motor Control
		rev = 1;
		if (vexRT[Btn8U]) {rev = -1;}
	  motor[UR] = vexRT[Btn6U] * 127 * rev;
	  motor[DR] = vexRT[Btn6D] * 127 * rev;
	  motor[UL] = vexRT[Btn5U] * 127 * rev;
	  motor[DL] = vexRT[Btn5D] * 127 * rev;
	}
}
