#pragma config(Sensor, in1,    RarmPoten,      sensorPotentiometer)
#pragma config(Sensor, in8,    armPoten,       sensorPotentiometer)
#pragma config(Motor,  port1,           FRWheel,       tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           FLWheel,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           RArm,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           RBLift,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           RALift,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           LALift,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           LBLift,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           LArm,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           BLWheel,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          BRWheel,       tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
	// Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;
}

task autonomous()
{

}
task usercontrol()
{
	int creep = 25;

	while (true)
	{
		//*Driver Controls ************************************************************************************************
		//Manual Lift Control
		motor[RBLift] = ((vexRT[Btn5U] - vexRT[Btn5D]) * 127) + ((vexRT[Btn7R] - vexRT[Btn7D]) * 127 );
		motor[LBLift] = ((vexRT[Btn5U] - vexRT[Btn5D]) * 127) + ((vexRT[Btn7U] - vexRT[Btn7L]) * 127 );
		motor[LALift] = ((vexRT[Btn5U] - vexRT[Btn5D]) * 127) + ((vexRT[Btn7U] - vexRT[Btn7L]) * 127 );
		motor[RALift] = ((vexRT[Btn5U] - vexRT[Btn5D]) * 127) + ((vexRT[Btn7U] - vexRT[Btn7L]) * 127 );

		//Manual Arm Control
		motor[RArm] = ( vexRT[Btn6U] - vexRT[Btn6D] ) * -127;
		motor[LArm] = ( vexRT[Btn6U] - vexRT[Btn6D] ) * 127;

		//Drive Wheels
		if ((vexRT[Ch3] < creep) && (vexRT[Ch3] >-creep) && (vexRT[Ch4] < creep) && (vexRT[Ch4] >-creep)){motor[FLWheel] = 0;} else {motor[FLWheel] = vexRT[Ch3] + vexRT[Ch4]; }
		if ((vexRT[Ch3] < creep) && (vexRT[Ch3] >-creep) && (vexRT[Ch1] < creep) && (vexRT[Ch1] >-creep)){motor[BLWheel] = 0;} else {motor[BLWheel] = vexRT[Ch3] - vexRT[Ch1]; }
		if ((vexRT[Ch2] < creep) && (vexRT[Ch2] >-creep) && (vexRT[Ch4] < creep) && (vexRT[Ch4] >-creep)){motor[FRWheel] = 0;} else {motor[FRWheel] = vexRT[Ch2] - vexRT[Ch4]; }
		if ((vexRT[Ch2] < creep) && (vexRT[Ch2] >-creep) && (vexRT[Ch1] < creep) && (vexRT[Ch1] >-creep)){motor[BRWheel] = 0;} else {motor[BRWheel] = vexRT[Ch2] + vexRT[Ch1]; }
	}
}
