#pragma config(Motor,  port1,           BRWheel,       tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           FRWheel,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           BLWheel,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           FLWheel,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           ConveyorWheel, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           CW2,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           Conveyor,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           C2,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           C3,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          C4,            tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
  // .....................................................................................
  // Insert user code here.
  // .....................................................................................

	AutonomousCodePlaceholderForTesting();  // Remove this function call once you have "real" code.
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	// User control code here, inside the loop

	while (true)
	{
	  motor[FRWheel] = vexRT[Ch2];
	  motor[BRWheel] = vexRT[Ch2];
	  motor[FLWheel] = vexRT[Ch3];
	  motor[BLWheel] = vexRT[Ch3];
	  motor[Conveyor] = vexRT[Btn8R] * 127;
	  motor[C2] = vexRT[Btn8R] * 127;
	  motor[C3] = vexRT[Btn8R] * 127;
	  motor[C4] = vexRT[Btn8R] * 127;
	  motor[ConveyorWheel] = vexRT[Btn8R] * 127;
	  motor[CW2] = vexRT[Btn8R] * 127;

	}
}
